// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBShlCRUIZgvlTl02fy44Y6H9lDhLp1v3w',
    appId: '1:622357614917:web:49ff4f93197331a31fae2c',
    messagingSenderId: '622357614917',
    projectId: 'sama-anwar-al-huda',
    authDomain: 'sama-anwar-al-huda.firebaseapp.com',
    storageBucket: 'sama-anwar-al-huda.firebasestorage.app',
    measurementId: 'G-VTK3XZ8S19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6eNvwqDemL02HJ8NL4j34kRwqPTIe_7g',
    appId: '1:622357614917:android:08ae097ad17fbd171fae2c',
    messagingSenderId: '622357614917',
    projectId: 'sama-anwar-al-huda',
    storageBucket: 'sama-anwar-al-huda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6wgTHnW0BHS2tr5Xi9RWSqc5G4bsofvQ',
    appId: '1:622357614917:ios:30e7288a837b09791fae2c',
    messagingSenderId: '622357614917',
    projectId: 'sama-anwar-al-huda',
    storageBucket: 'sama-anwar-al-huda.firebasestorage.app',
    iosBundleId: 'com.sama.samaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6wgTHnW0BHS2tr5Xi9RWSqc5G4bsofvQ',
    appId: '1:622357614917:ios:30e7288a837b09791fae2c',
    messagingSenderId: '622357614917',
    projectId: 'sama-anwar-al-huda',
    storageBucket: 'sama-anwar-al-huda.firebasestorage.app',
    iosBundleId: 'com.sama.samaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBShlCRUIZgvlTl02fy44Y6H9lDhLp1v3w',
    appId: '1:622357614917:web:98f480d95c06192b1fae2c',
    messagingSenderId: '622357614917',
    projectId: 'sama-anwar-al-huda',
    authDomain: 'sama-anwar-al-huda.firebaseapp.com',
    storageBucket: 'sama-anwar-al-huda.firebasestorage.app',
    measurementId: 'G-5ELW32D0ZB',
  );
}
